### ISSUE TITLE
Photographers ulan link instead of wikidata

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vocab-app#24]
For some photographers the "view at wikidata " button opens a ulan link instead of a wikidata link.

I think that happens because these photographers have also been included in the reconciliation list of artists

i.e.: Boissonas family

https://vocab.artresearch.net/resource/?partner=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&partnerimage=itatti.png&subject=https%3A%2F%2Fartresearch.net%2Fresource%2Fitatti%2Factor%2F9000425221&uri=Default%3AConfirmPhotographer

**Comment by sophisid** [comment]
Yes, you are right. How do you want to handle this? Put all the photographers that have wikidata to the artists list, or leave them at the photographers list?
