### ISSUE TITLE
Numbers - Statistics

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vocab-app#25]
Can you please check if the counts in the statistics are correct?

It seems that now there have been reconciled 106 out of 539 I Tatti photographers. However, the List of photographer matchings right now includes 11 names. Similar problems there are with repositeries and artists of all providers.

Are there names missing from the lists or are the counts in the statistics page wrong?

**Comment by spykoulouris** [comment]
<img width="1659" alt="Screenshot 2022-06-23 at 09 20 21" src="https://user-images.githubusercontent.com/73180833/175229350-4eed0b7a-449c-4a3d-8acb-4d67049fd97d.png">

<img width="1743" alt="Screenshot 2022-06-23 at 09 20 53" src="https://user-images.githubusercontent.com/73180833/175229368-6275870f-eea1-41ab-b632-89970ecd1ac5.png">

**Comment by sophisid** [comment]
@spykoulouris some of them are automatically done. That's why it shows more than the dashboard.

**Comment by sophisid** [comment]
Changed the numbers in the statistics, still many remaining that you do not see, because they do not have close matches and we have hide them for now, eventually we will activate them again
