### ISSUE TITLE
Added the "has part" "is part of" relation

### ISSUE THREAD

**Issue by sophisid** [ArtResearch/vocab-app#26]
I have added the has part and is part of relation for repositories please review.

**Comment by spykoulouris** [comment]
Can you send some examples? I see no part relations for the Louvre, Vatican Museums, or the Uffizi gallery

**Comment by sophisid** [comment]
sorry my mistake, did not uploaded the changes 
https://vocab.artresearch.net/resource/?partner=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&partnerimage=zeri.png&subject=https%3A%2F%2Fartresearch.net%2Fresource%2Fzeri%2Factor%2F11F528EA-0A33-3EA0-A3AE-D1B6CC0F1CE4&uri=Default%3AConfirmRepository
![image](https://user-images.githubusercontent.com/55842445/197506691-51f506c6-fc5d-445f-b9d1-cfe1133d325d.png)

**Comment by spykoulouris** [comment]
I see. That looks great, thanks.
