### ISSUE TITLE
Statistics Vocab

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/vocab-app#5]
Create pie charts for the reconciliation process

* Reconciled (Generic - total)
* Reconciled with ULAN / Wikidata
* Reconciled with a Pharos Generated URI

**Comment by mafragias** [comment]
We could also have a progress bar showing in each regarding reconciliation page.

**Comment by AndreasMichelakis** [comment]
Additional description:
List of users and related statistics about their activity (e.g. top 10 list of users that reconciled artists)

**Comment by mafragias** [comment]
@AndreasMichelakis  still no statics in vocab.

**Comment by AndreasMichelakis** [comment]
This is now online. Please let us know if anything else is need for this.
